### ISSUE TITLE
Group Mode Case 2 (Utang Tracker)

### ISSUE THREAD

**Issue by crees-bree** [crees-bree/Barkada-Budget-Calculator#4]
- [x] Create menu for case 2 to:
  - [x] Display who paid and didn't pay yet
  - [x] Add a new member (name, payment, date sa payment (automatically set to today), bill)
    - [x] Tagai siyag option na makaedit siya before i add ang member
  - [x] Iupdate ang gibayran sa member (just like adding a new record sa person mode)
    - [x] Also iupdate ang date to today
    - [x] Allow user to edit record before niya isave (edit payment & date)
  - [x] Edit a member
  - [x] Delete a member
  - [x] Display each member details (name, bill, payment so far, when siya nibayad)

please ko edit sa to-do if naa pa bay ma add
